 # download Lemontree.Automation on a runner and setup the license
name: Lemon Tree Automation Demo script

on:
  push:
    branches:
      - main

jobs:
  test-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run getLTA.ps1 script
      shell: pwsh  # Use PowerShell Core (pwsh) on the runner
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
            .\getLTA.ps1 -License .\LTALicense\license.lic -model .\DemoModel.eapx 
